
services:
  api-gateway:
    image: api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - storage-service

  user-service:
    image: user-service
    build:
      context: ./user-service
      dockerfile: Dockerfile
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/user_bot
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8081:8081"


  storage-service:
    image: storage-service
    build:
      context: ./storage-service
      dockerfile: Dockerfile
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/storage_bot
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8082:8082"


  telegram-bot:
    image: telegram-bot
    build:
      context: ./telegram-bot
      dockerfile: Dockerfile
    environment:
      BOT_TOKEN: "7746537029:AAEStDE86nMTrYC_Lx-Zbo-Dl8H9zWX1snk"
      API_GATEWAY_URL: "http://api-gateway:8080"
    depends_on:
      - user-service
      - storage-service
