
BOT_TOKEN = "7746537029:AAEStDE86nMTrYC_Lx-Zbo-Dl8H9zWX1snk"

API_GATEWAY_URL = "http://localhost:8080"
USER_REGISTRATION_URL = f"{API_GATEWAY_URL}/api/users/register"
STORAGE_URL = f"{API_GATEWAY_URL}/api/movies"